### ISSUE TITLE
Module Not Found

### ISSUE THREAD

**Issue by iamtherealramz** [ContentAutomation/TwitchCompilationCreator#14]
```
C:\Users\Ramz\Downloads\TwitchCompilationCreator-main\TwitchCompilationCreator-main>poetry run python main.py
Traceback (most recent call last):
  File "C:\Users\Ramz\Downloads\TwitchCompilationCreator-main\TwitchCompilationCreator-main\main.py", line 1, in <module>
    from src.ClipHandler import ClipHandler
  File "C:\Users\Ramz\Downloads\TwitchCompilationCreator-main\TwitchCompilationCreator-main\src\ClipHandler.py", line 5, in <module>
    import numpy as np
ModuleNotFoundError: No module named 'numpy'
```
I've followed the guide and got this error appear. I have numpy already installed before starting the guide.

**Comment by lucaSchilling** [comment]
Where have you installed numpy? Poetry uses venvs so I guess poetry run will use the venv which has no numpy installed. Have you performed "poetry install" prior to this?

**Comment by iamtherealramz** [comment]
I tried it both on my main pc and side pc which was first time using poetry on both of them devices. I did try to uninstall and reinstall poetry on my main pc when this issue occurred. 

I used pip to install numpy so it should be in default python directory.

**Comment by lucaSchilling** [comment]
But did you install numpy into the correct virtual environment? You can use `poetry show -v` to check which virtualenv is used and what packages are installed. And again did you run `poetry install` before using  `poetry run` ?

**Comment by iamtherealramz** [comment]
Ahh no I didn't, Sorry about that. Mistook that for the installation of poetry part. Ran it and it installed all the dependencies needed. 

After installing all the dependencies, I do still get an error.

```
Microsoft Windows [Version 10.0.19042.1110]
(c) Microsoft Corporation. All rights reserved.

C:\Users\Ramz\Downloads\TwitchCompilationCreator-main\TwitchCompilationCreator-main>poetry run python main.py
Traceback (most recent call last):
  File "C:\Users\Ramz\AppData\Local\pypoetry\Cache\virtualenvs\twitchcompilationcreator-JoBoRbEs-py3.8\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 64, in <module>
    from tensorflow.python._pywrap_tensorflow_internal import *
ImportError: DLL load failed while importing _pywrap_tensorflow_internal: A dynamic link library (DLL) initialization routine failed.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 1, in <module>
    from src.ClipHandler import ClipHandler
  File "C:\Users\Ramz\Downloads\TwitchCompilationCreator-main\TwitchCompilationCreator-main\src\ClipHandler.py", line 8, in <module>
    import tensorflow as tf
  File "C:\Users\Ramz\AppData\Local\pypoetry\Cache\virtualenvs\twitchcompilationcreator-JoBoRbEs-py3.8\lib\site-packages\tensorflow\__init__.py", line 41, in <module>
    from tensorflow.python.tools import module_util as _module_util
  File "C:\Users\Ramz\AppData\Local\pypoetry\Cache\virtualenvs\twitchcompilationcreator-JoBoRbEs-py3.8\lib\site-packages\tensorflow\python\__init__.py", line 39, in <module>
    from tensorflow.python import pywrap_tensorflow as _pywrap_tensorflow
  File "C:\Users\Ramz\AppData\Local\pypoetry\Cache\virtualenvs\twitchcompilationcreator-JoBoRbEs-py3.8\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 83, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "C:\Users\Ramz\AppData\Local\pypoetry\Cache\virtualenvs\twitchcompilationcreator-JoBoRbEs-py3.8\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 64, in <module>
    from tensorflow.python._pywrap_tensorflow_internal import *
ImportError: DLL load failed while importing _pywrap_tensorflow_internal: A dynamic link library (DLL) initialization routine failed.


Failed to load the native TensorFlow runtime.

See https://www.tensorflow.org/install/errors

for some common reasons and solutions.  Include the entire stack trace
above this error message when asking for help.

C:\Users\Ramz\Downloads\TwitchCompilationCreator-main\TwitchCompilationCreator-main>poetry show -v
Using virtualenv: C:\Users\Ramz\AppData\Local\pypoetry\Cache\virtualenvs\twitchcompilationcreator-JoBoRbEs-py3.8
absl-py                 0.13.0    Abseil Python Common Libraries, see https://github.com/abseil/abseil-py.
astunparse              1.6.3     An AST unparser for Python
cachetools              4.2.2     Extensible memoizing collections and decorators
certifi                 2021.5.30 Python package for providing Mozilla's CA Bundle.
chardet                 4.0.0     Universal encoding detector for Python 2 and 3
decorator               4.4.2     Decorators for Humans
flatbuffers             1.12      The FlatBuffers serialization format for Python
gast                    0.3.3     Python AST that abstracts the underlying Python version
google-auth             1.32.0    Google Authentication Library
google-auth-oauthlib    0.4.4     Google Authentication Library
google-pasta            0.2.0     pasta is an AST-based Python refactoring library
grpcio                  1.32.0    HTTP/2-based RPC framework
h5py                    2.10.0    Read and write HDF5 files from Python
idna                    2.10      Internationalized Domain Names in Applications (IDNA)
imageio                 2.9.0     Library for reading and writing a wide range of image, video, scientific, and vol...
imageio-ffmpeg          0.4.4     FFMPEG wrapper for Python
iso-639                 0.4.5     Python library for ISO 639 standard
iso3166                 1.0.1     Self-contained ISO 3166-1 country definitions.
isodate                 0.6.0     An ISO 8601 date/time/duration parser and formatter
jinja2                  2.11.3    A very fast and expressive template engine.
keras-preprocessing     1.1.2     Easy data preprocessing and data augmentation for deep learning models
markdown                3.3.4     Python implementation of Markdown.
markupsafe              2.0.1     Safely add untrusted strings to HTML/XML markup.
moviepy                 1.0.3     Video editing with Python
numpy                   1.19.5    NumPy is the fundamental package for array computing with Python.
oauthlib                3.1.1     A generic, spec-compliant, thorough implementation of the OAuth request-signing l...
opt-einsum              3.3.0     Optimizing numpys einsum function
pillow                  8.2.0     Python Imaging Library (Fork)
proglog                 0.1.9     Log and progress bar manager for console, notebooks, web...
protobuf                3.17.3    Protocol Buffers
pyasn1                  0.4.8     ASN.1 types and codecs
pyasn1-modules          0.2.8     A collection of ASN.1-based protocols modules.
pycryptodome            3.10.1    Cryptographic library for Python
pysocks                 1.7.1     A Python SOCKS client module. See https://github.com/Anorov/PySocks for more info...
requests                2.25.1    Python HTTP for Humans.
requests-oauthlib       1.3.0     OAuthlib authentication support for Requests.
rsa                     4.7.2     Pure-Python RSA implementation
six                     1.15.0    Python 2 and 3 compatibility utilities
streamlink              2.2.0     Streamlink is a command-line utility that extracts streams from various services ...
tensorboard             2.5.0     TensorBoard lets you watch Tensors Flow
tensorboard-data-server 0.6.1     Fast data loading for TensorBoard
tensorboard-plugin-wit  1.8.0     What-If Tool TensorBoard plugin.
tensorflow              2.4.2     TensorFlow is an open source machine learning framework for everyone.
tensorflow-estimator    2.4.0     TensorFlow Estimator.
termcolor               1.1.0     ANSII Color formatting for output in terminal.
tqdm                    4.61.1    Fast, Extensible Progress Meter
typing-extensions       3.7.4.3   Backported and Experimental Type Hints for Python 3.5+
urllib3                 1.26.6    HTTP library with thread-safe connection pooling, file post, and more.
websocket-client        1.1.0     WebSocket client for Python with low level API options
werkzeug                2.0.1     The comprehensive WSGI web application library.
wrapt                   1.12.1    Module for decorators, wrappers and monkey patching.

C:\Users\Ramz\Downloads\TwitchCompilationCreator-main\TwitchCompilationCreator-main>
```

**Comment by ChristianCoenen** [comment]
https://stackoverflow.com/questions/60474219/tensorflow-importerror-dll-load-failed-a-dynamic-link-library-dll-initiali

**Comment by iamtherealramz** [comment]
Yep that seemed to fix it, rendered a video out fully and it seems fine. Thank you for all the help and such quick replies @ChristianCoenen and @lucaSchilling!
