### ISSUE TITLE
streamlink.exceptions.StreamError:

### ISSUE THREAD

**Issue by OneClickPablo123** [ContentAutomation/TwitchCompilationCreator#19]
Hi, at some point the Bot gives me this Error:

info:root:Adding new valid clip: Clip zum Tot by MontanaBlack88
info:root:Status Code: 200 -> handling response data now
info:root:New pagination: eyJiIjpudWxsLCJhIjp7IkN1cnNvciI6Ik5EQXcifX0
Traceback (most recent call last):
  File "/home/pablo/.cache/pypoetry/virtualenvs/twitchcompilationcreator-_qx3GjyT-py3.8/lib/python3.8/site-packages/streamlink/plugin/api/http_session.py", line 160, in request
    res.raise_for_status()
  File "/home/pablo/.cache/pypoetry/virtualenvs/twitchcompilationcreator-_qx3GjyT-py3.8/lib/python3.8/site-packages/requests/models.py", line 943, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error:  for url: https://production.assets.clips.twitchcdn.net/AT-cm%7ClhUD7Y13uOHAD7xBG7Azew.mp4?sig=03c8ef4078b909a526520055f3aea26a813f2e24&token=%7B%22authorization%22%3A%7B%22forbidden%22%3Atrue%2C%22reason%22%3A%22GEOBLOCKED%22%7D%2C%22clip_uri%22%3A%22https%3A%2F%2Fproduction.assets.clips.twitchcdn.net%2FAT-cm%257ClhUD7Y13uOHAD7xBG7Azew.mp4%22%2C%22device_id%22%3Anull%2C%22expires%22%3A1634224325%2C%22user_id%22%3A%22%22%2C%22version%22%3A2%7D

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 17, in <module>
    ch.get_clips(
  File "/home/pablo/Schreibtisch/Twitch/TwitchCompilationCreator/src/ClipHandler.py", line 46, in get_clips
    self.get_game_clips(utils.get_headers(), timespan, language, kwargs)
  File "/home/pablo/Schreibtisch/Twitch/TwitchCompilationCreator/src/ClipHandler.py", line 78, in get_game_clips
    self.handle_response_data(resp.json(), language, creator_counts, filter_information)
  File "/home/pablo/Schreibtisch/Twitch/TwitchCompilationCreator/src/ClipHandler.py", line 123, in handle_response_data
    clip_path = self.download_clip(clip)
  File "/home/pablo/Schreibtisch/Twitch/TwitchCompilationCreator/src/ClipHandler.py", line 155, in download_clip
    with open(output_file, "wb") as f, stream.open() as fd:
  File "/home/pablo/.cache/pypoetry/virtualenvs/twitchcompilationcreator-_qx3GjyT-py3.8/lib/python3.8/site-packages/streamlink/stream/http.py", line 70, in open
    res = self.session.http.request(method=method,
  File "/home/pablo/.cache/pypoetry/virtualenvs/twitchcompilationcreator-_qx3GjyT-py3.8/lib/python3.8/site-packages/streamlink/plugin/api/http_session.py", line 168, in request
    raise err
streamlink.exceptions.StreamError: Unable to open URL: https://production.assets.clips.twitchcdn.net/AT-cm%7ClhUD7Y13uOHAD7xBG7Azew.mp4?sig=03c8ef4078b909a526520055f3aea26a813f2e24&token=%7B%22authorization%22%3A%7B%22forbidden%22%3Atrue%2C%22reason%22%3A%22GEOBLOCKED%22%7D%2C%22clip_uri%22%3A%22https%3A%2F%2Fproduction.assets.clips.twitchcdn.net%2FAT-cm%257ClhUD7Y13uOHAD7xBG7Azew.mp4%22%2C%22device_id%22%3Anull%2C%22expires%22%3A1634224325%2C%22user_id%22%3A%22%22%2C%22version%22%3A2%7D (404 Client Error:  for url: https://production.assets.clips.twitchcdn.net/AT-cm%7ClhUD7Y13uOHAD7xBG7Azew.mp4?sig=03c8ef4078b909a526520055f3aea26a813f2e24&token=%7B%22authorization%22%3A%7B%22forbidden%22%3Atrue%2C%22reason%22%3A%22GEOBLOCKED%22%7D%2C%22clip_uri%22%3A%22https%3A%2F%2Fproduction.assets.clips.twitchcdn.net%2FAT-cm%257ClhUD7Y13uOHAD7xBG7Azew.mp4%22%2C%22device_id%22%3Anull%2C%22expires%22%3A1634224325%2C%22user_id%22%3A%22%22%2C%22version%22%3A2%7D)

Can some one Help me out with this?

Greetings

**Comment by MorMundHS-MA** [comment]
Closing due to inactivity. Feel free to comment if the issue persisted.
